version: '2'
services:
  fleet-supervisor:
    build: ./fleet-supervisor
    restart: on-failure
    network_mode: host
    privileged: true
    ports:
      - 3000:3000
    labels:
      io.balena.features.supervisor-api: 1
  roon-bridge:
    build: ./roon-bridge
    restart: on-failure
    network_mode: host
    ports:
      - 9003:9003
      - 9100-9200:9100-9200
    privileged: true
    volumes:
      - roon-bridge:/opt/RoonBridge
volumes:
  roon-bridge:
