version: '2'
services:
  roon-bridge:
    build: ./roon-bridge
    restart: on-failure
    network_mode: host
    privileged: true
    volumes:
      - roon-bridge:/var/roon
      - roon-bridge:/opt/RoonBridge
